Add error trap to CI workflow scripts
An error trap has been added to both the ci-docker.yml and ci-host.yml scripts within the GitHub workflow. This new line of code will now output "Failed running tests" when a test failure occurs, providing more transparent and immediate feedback during integration testing and debugging.

diff --git a/.github/workflows/ci-host.yml b/.github/workflows/ci-host.yml
--- a/.github/workflows/ci-host.yml
+++ b/.github/workflows/ci-host.yml
@@ -81,4 +81,6 @@ jobs:
           CHAIN_ID: poktroll
           ENDPOINT: https://testnet-validated-validator-rpc.poktroll.com
         continue-on-error: true
-        run: yarn test:ci
+        run: |
+          trap 'echo "Failed running tests"' ERR
+          yarn test:ci
